[pytest]
markers =
    change: Tests that modify name of  a user
    check: Tests that check users name
    http: Tests that check http protocol
    api: маркер для API-тестів
    repo: імʼя репозиторія 
    database: маркер для перевірки підключення до бази даних